"""
TTS service using Coqui TTS (Open Source, local).
Produces high-quality audio for podcast generation without external API keys.
"""
import asyncio
import os
import torch
from typing import List, Dict, Any, Optional
from TTS.api import TTS
from concurrent.futures import ThreadPoolExecutor

from app.core.config import settings

# Bypass the "Agree to terms" prompt
os.environ["COQUI_TOS_AGREED"] = "1"

class ElevenLabsService:
    """TTS service wrapping Coqui TTS (Local)."""

    def __init__(self):
        self.model_name = "tts_models/en/vctk/vits"
        self.tts = None
        self.executor = ThreadPoolExecutor(max_workers=10)
        # Default speakers for VCTK VITS
        self.default_male_voice = "p226"   # Dr. Alex
        self.default_female_voice = "p225" # Prof. Jamie
        self._load_model()

    def _load_model(self):
        """Load the model synchronously (run on init)."""
        if self.tts is None:
            print(f"Loading Coqui TTS model: {self.model_name}...")
            self.tts = TTS(model_name=self.model_name, progress_bar=False, gpu=False)
            print("Coqui TTS model loaded successfully.")

    def _generate_sync(self, text: str, voice: str, output_path: str):
        """Synchronous generation to be run in executor."""
        self.tts.tts_to_file(text=text, speaker=voice, file_path=output_path)

    async def generate_speech(
        self,
        text: str,
        voice: str,
        speed: float = 1.0
    ) -> bytes:
        """Generate speech bytes from text using Coqui TTS."""
        import tempfile
        
        # Create a temp file for the output
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
            tmp_path = tmp.name
        
        try:
            # Run the synchronous TTS in a thread
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(self.executor, self._generate_sync, text, voice, tmp_path)
            
            # Read the generated bytes
            with open(tmp_path, "rb") as f:
                audio_bytes = f.read()
            
            return audio_bytes
        finally:
            # Clean up temp file
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    async def generate_podcast_audio(
        self,
        script: List[Dict[str, Any]],
        voice_male: Optional[str] = None,
        voice_female: Optional[str] = None,
        speed: float = 1.0
    ) -> tuple[bytes, float]:
        """Generate full podcast audio in parallel."""

        male_voice  = voice_male  or self.default_male_voice
        female_voice = voice_female or self.default_female_voice

        # Prepare tasks for parallel execution
        async def process_segment(entry, index):
            speaker = entry.get("speaker", "A")
            text = entry.get("text", "").strip()
            if not text or entry.get("is_recap", False):
                return None
            
            voice = male_voice if speaker == "A" else female_voice
            segment = await self.generate_speech(text=text, voice=voice, speed=speed)
            
            if segment:
                # Strip WAV header (first 44 bytes) for joining after first
                raw_audio = segment[44:] if index > 0 else segment
                seg_duration = len(raw_audio) / (22050 * 1 * 2)
                entry["duration"] = seg_duration
                return raw_audio, seg_duration
            return None

        # Run all segments in parallel
        tasks = [process_segment(entry, i) for i, entry in enumerate(script)]
        results = await asyncio.gather(*tasks)

        audio_parts: List[bytes] = []
        total_duration = 0.0
        
        for i, res in enumerate(results):
            if res:
                raw_audio, seg_dur = res
                audio_parts.append(raw_audio)
                total_duration += seg_dur
                
                # Add 1.5s silence gap
                silence_duration = 1.5
                audio_parts.append(b"\x00" * int(silence_duration * 22050 * 2))
                total_duration += silence_duration

        return b"".join(audio_parts), total_duration

    def get_available_voices(self) -> List[Dict[str, str]]:
        return [
            # Top Picks
            {"id": "p226", "name": "Brian (Engaging Male)"},
            {"id": "p225", "name": "Jenny (Friendly Female)"},
            {"id": "p232", "name": "Arthur (Deep Male)"},
            {"id": "p229", "name": "Sarah (Soft Female)"},
            # American Accents (approximate)
            {"id": "p311", "name": "David (American Male)"},
            {"id": "p310", "name": "Emily (American Female)"},
            # More Varieties
            {"id": "p240", "name": "Grace (Clear Female)"},
            {"id": "p243", "name": "James (Steady Male)"},
            {"id": "p236", "name": "Oliver (Brisk Male)"},
            {"id": "p244", "name": "Eleanor (Warm Female)"},
        ]


# Singleton
elevenlabs_service = ElevenLabsService()
